In [1]:
import numpy as np

In [2]:
a_02 = np.array([0,1,2,3,4])
print(a_02)

[0 1 2 3 4]


In [3]:
a_02.ndim

1

In [4]:
a_02.shape

(5,)

In [5]:
b_02 = np.array([[5,6,7,8,9],[9,8,7,6,5]])
print(b_02)

[[5 6 7 8 9]
 [9 8 7 6 5]]


In [6]:
b_02.ndim

2

In [7]:
b_02.shape

(2, 5)

(2, 5)

In [8]:
c_02 = np.array([[[1,2,4,6,8],[9,2,3,5,7],[0,2,2,5,8],[9,4,6,2,3],[0,9,8,7,6]],
              [[11,32,64,72,33],[99,45,36,72,64],[11,22,33,44,55],[66,77,88,99,110],[888,777,666,555,444]],
              [[123,234,345,456,567],[321,432,543,654,765],[678,789,910,911,313],[135,215,313,131,121],[145,541,415,514,451]]])
print(c_02)

[[[  1   2   4   6   8]
  [  9   2   3   5   7]
  [  0   2   2   5   8]
  [  9   4   6   2   3]
  [  0   9   8   7   6]]

 [[ 11  32  64  72  33]
  [ 99  45  36  72  64]
  [ 11  22  33  44  55]
  [ 66  77  88  99 110]
  [888 777 666 555 444]]

 [[123 234 345 456 567]
  [321 432 543 654 765]
  [678 789 910 911 313]
  [135 215 313 131 121]
  [145 541 415 514 451]]]


In [9]:
c_02.ndim

3

In [10]:
c_02.shape

(3, 5, 5)

In [11]:
c_02[0,0]

array([1, 2, 4, 6, 8])

In [12]:
c_02[0,2,3]

5

In [13]:
c_02[1,3,3]

99

In [14]:
c_02[0,:]

array([[1, 2, 4, 6, 8],
       [9, 2, 3, 5, 7],
       [0, 2, 2, 5, 8],
       [9, 4, 6, 2, 3],
       [0, 9, 8, 7, 6]])

In [15]:
c_02[:,2]

array([[  0,   2,   2,   5,   8],
       [ 11,  22,  33,  44,  55],
       [678, 789, 910, 911, 313]])

In [16]:
c_02[0,1:4]

array([[9, 2, 3, 5, 7],
       [0, 2, 2, 5, 8],
       [9, 4, 6, 2, 3]])

In [17]:
#Baris ke-2 pada matrix c_02

c_02[:,1]

array([[  9,   2,   3,   5,   7],
       [ 99,  45,  36,  72,  64],
       [321, 432, 543, 654, 765]])

In [18]:
#Kolom ke-3 pada matrix c_02

c_02[:,:,2]

array([[  4,   3,   2,   6,   8],
       [ 64,  36,  33,  88, 666],
       [345, 543, 910, 313, 415]])

In [19]:
#Menentukan anggota pada matrix ke-3 baris ke-4 kolom ke-2 pada matrix c_02

c_02[2,3,1]

215

In [20]:
#Menentukan anggota pada matrix ke-2 baris ke-3 kolom ke-4 pada matrix c_02

c_02[1,2,3]

44

In [21]:
#Menentukan anggota pada matrix ke-1 baris ke-5 kolom ke-1 pada matrix c_02

c_02[0,4,0]

0

In [22]:
#Matriks dengan anggota 1, dengan baris dan kolom sesuai dengan yang diinput.

np.ones((2,2))#Matriks dengan anggota 1, dengan baris 2 dan kolom 2.

array([[1., 1.],
       [1., 1.]])

In [23]:
#Matriks dengan anggota 1, dengan baris 10 dan kolom 10.

np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
#Matriks dengan anggota 0, dengan baris dan kolom sesuai dengan yang diinput.

np.zeros((4,3))#Matriks dengan anggota 0, dengan baris 4 dan kolom 3.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#Matriks dengan anggota 0, dengan banyak matriks, baris dan kolom sesuai dengan yang diinput.

np.zeros((2,3,4))#Matriks dengan anggota 0, dengan banyak matriks sebanyak 2, baris 3 dan kolom 4.

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
#Mencetak matriks identitas, dengan baris dan kolom sesuai dengan yang diinput.

np.identity(4)#Matriks identitas dengan ordo 4 x 4.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#Mencetak matriks dengan baris, kolom, dan anggota sesuai dengan yang diinput.

np.full((4,5),7)#Matriks dengan baris 4, kolom 5, dan anggotanya 7.

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [32]:
#Matriks dengan baris dan kolom sesuai dengan yang diinput, namun dengan anggota yang random.

np.random.rand(2,3)#Matriks dengan baris 2 dan kolom 3 dengan anggota random.

array([[0.48568945, 0.04131099, 0.73953784],
       [0.58808478, 0.5868746 , 0.90462632]])

In [34]:
#Matriks dengan anggota integer random dengan skala dan ukuran yang diinput

np.random.randint(1,10,size=(3,4))#Matriks dengan anggota integer 1-10 dengan ordo 3 x 4.

array([[4, 7, 3, 8],
       [6, 5, 9, 4],
       [4, 1, 8, 4]])

In [35]:
r_02 = np.array([3,4,5,6,7])
print(r_02)

[3 4 5 6 7]


In [36]:
g_02 = r_02
print(g_02)

[3 4 5 6 7]


In [37]:
g_02[2] = 2
print(g_02)

[3 4 2 6 7]


In [38]:
print(r_02)

[3 4 2 6 7]


In [40]:
rgh_02 = ([11,22,33,44])
print(rgh_02)

[11, 22, 33, 44]


In [41]:
rnr_02 = rgh_02.copy()
print(rnr_02)

[11, 22, 33, 44]


In [42]:
rnr_02[0] = 55
print(rnr_02)

[55, 22, 33, 44]


In [43]:
print(rgh_02)

[11, 22, 33, 44]


In [56]:
rgh_02 = np.array([11,22,33,44])
print("Diketahui matriks rgh_02 sebagai berikut: rgh_02 =" , rgh_02)
print('_______________________________________________________________')

print("Penjumlahan matriks rgh_02 dengan 2")
print(rgh_02+2)
print('_______________________________________________________________')

print("Pengurangan matriks rgh_02 dengan 2")
print(rgh_02-2)
print('_______________________________________________________________')

print("Perkalian matriks rgh_02 dengan 2")
print(rgh_02*2)
print('_______________________________________________________________')

print("Pembagian matriks rgh_02 dengan 2")
print(rgh_02/2)
print('_______________________________________________________________')

print("Matriks rgh_02 dipangkatkan dengan 2")
print(rgh_02**2)
print('_______________________________________________________________')

Diketahui matriks rgh_02 sebagai berikut: rgh_02 = [11 22 33 44]
_______________________________________________________________
Penjumlahan matriks rgh_02 dengan 2
[13 24 35 46]
_______________________________________________________________
Pengurangan matriks rgh_02 dengan 2
[ 9 20 31 42]
_______________________________________________________________
Perkalian matriks rgh_02 dengan 2
[22 44 66 88]
_______________________________________________________________
Pembagian matriks rgh_02 dengan 2
[ 5.5 11.  16.5 22. ]
_______________________________________________________________
Matriks rgh_02 dipangkatkan dengan 2
[ 121  484 1089 1936]
_______________________________________________________________


In [63]:
rgh_02 = np.array([11,22,33,44])
rnr_02 = np.array([1,2,3,4])
hasil_perkalian_matriks_02 = rgh_02*rnr_02
print("Diberikan matriks rgh_02 dan rnr_02 sebagai berikut:")
print("Matriks rgh_02=" , rgh_02)
print("Matriks rnr_02=" , rnr_02)
print('_______________________________________________________________')

print("Perkalian matriks rgh_02 dengan matriks rnr_02")
print(hasil_perkalian_matriks_02)
print('_______________________________________________________________')

Diberikan matriks rgh_02 dan rnr_02 sebagai berikut:
Matriks rgh_02= [11 22 33 44]
Matriks rnr_02= [1 2 3 4]
_______________________________________________________________
Perkalian matriks rgh_02 dengan matriks rnr_02
[ 11  44  99 176]
_______________________________________________________________


In [66]:
npwp_02 = np.array([[1,3,5,7],
                    [2,4,6,8],
                    [1,2,3,4]])
print(npwp_02)

[[1 3 5 7]
 [2 4 6 8]
 [1 2 3 4]]


In [67]:
pwnp_02 = np.min(npwp_02)
print(pwnp_02)

1


In [71]:
ppnw_02 = np.min(npwp_02,axis=0)
print(ppnw_02)

[1 2 3 4]


In [72]:
wwnp_02 = np.min(npwp_02,axis=1)
print(wwnp_02)

[1 2 1]


In [74]:
pppp_02 = np.max(npwp_02)
print(pppp_02)

8


In [75]:
pppw_02 = np.max(npwp_02,axis=0)
print(pppw_02)

[2 4 6 8]


In [76]:
wppp_02 = np.max(npwp_02,axis=1)
print(wppp_02)

[7 8 4]
